[package]
name = "mc-server-wrapper-lib"
version = "0.1.0"
authors = ["Cldfire"]
edition = "2018"

[dependencies]
chrono = "0.4"
tokio = { version = "0.2", features = ["full"] }

[dev-dependencies]
rusty-hook = "^0.11.1"
