[package]
name = "mc-server-wrapper"
version = "0.1.0"
authors = ["Cldfire"]
edition = "2018"

[dependencies]
mc-server-wrapper-lib = { path = "../mc-server-wrapper-lib" }
structopt = "0.3"
indicatif = "0.14"
tokio = { version = "0.2", features = ["full"] }
dotenv = "0.15"
twilight = { git = "https://github.com/twilight-rs/twilight.git" }
minecraft-chat = "0.1"
log = "0.4"
fern = "0.6"
chrono = "0.4"
