[package]
name = "mc-server-wrapper"
version = "0.1.0"
license = "MIT OR Apache-2.0"
authors = ["Cldfire"]
edition = "2018"

[dependencies]
mc-server-wrapper-lib = { path = "../mc-server-wrapper-lib" }
structopt = "0.3"
tokio = { version = "0.2", features = ["full"] }
futures = "0.3"
twilight-http = "0.1"
twilight-gateway = "0.1"
twilight-cache-inmemory = "0.1"
twilight-model = "0.1"
twilight-command-parser = "0.1"
minecraft-protocol = "0.1"
log = "0.4"
fern = "0.6"
log-panics = "2.0"
chrono = "0.4"
once_cell = "1.4"
scopeguard = "1.1"
anyhow = "1.0"
crossterm = { version = "0.17", features = ["event-stream"] }
tui = { version = "0.10", default-features = false, features = ['crossterm'] }
unicode-width = "0.1"
ringbuffer = "0.2.2"
textwrap = "0.12"
toml = "0.5"
serde = "1.0"
serde_derive = "1.0"
notify = "4.0"

[dev-dependencies]
rusty-hook = "^0.11.1"
